### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zootedb0t** [zootedb0t/orcnvim#24]
- [x] Change auto-pair plugin to https://github.com/altermo/ultimate-autopair.nvim
- [x] `cmp-nvim` tab mapping broken

**Comment by zootedb0t** [comment]
- [x] Don't disable all inbuilt lsp-formatter

**Comment by zootedb0t** [comment]
- [x] Try https://github.com/stevearc/conform.nvim for formatting.

**Comment by zootedb0t** [comment]
- [x] Move to [none-ls](https://github.com/nvimtools/none-ls.nvim) for lint.

**Comment by zootedb0t** [comment]
- [x] Move from [alpha.nvim](https://github.com/goolord/alpha-nvim/) to [dashboard-nvim](https://github.com/nvimdev/dashboard-nvim)
- [x] Add footer in dashboard-nvim
- [x] Add config button in dashboard.
- [x] Add [Treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context)
- [x] Remove [peek.nvim](https://github.com/toppair/peek.nvim)

**Comment by zootedb0t** [comment]
- [x] Add super-tab keymap to `nvim-cmp`
- [x] Customise telescope border
- [x] Find alternative to [peek.nvim](https://github.com/toppair/peek.nvim) -> [markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim)

**Comment by zootedb0t** [comment]
- [x] Improve Statuscolumn
- [x] Remove [markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim) -> [peek.nvim](https://github.com/toppair/peek.nvim)

**Comment by zootedb0t** [comment]
- [x] LSP sign override broken on nightly.

**Comment by zootedb0t** [comment]
- [x] Improve statusline diagnostic function. [see](https://github.com/neovim/neovim/commit/4ee656e4f35766bef4e27c5afbfa8e3d8d74a76c)

**Comment by zootedb0t** [comment]
- [x] Use builtin `vim.snippet` for snippets, instead of `luasnip`.
- [x] Remove [Comment.nvim](https://github.com/numToStr/Comment.nvim) as we have this [builtin](https://github.com/neovim/neovim/commit/73de98256cf3932dca156fbfd0c82c1cc10d487e).

**Comment by zootedb0t** [comment]
- [x] Update lsp keymapping which are already default. [see](https://github.com/neovim/nvim-lspconfig/commit/7133e85c3df14a387da8942c094c7edddcdef309)

**Comment by zootedb0t** [comment]
- [x] Use  [nvim-highlight-colors ](https://github.com/brenoprata10/nvim-highlight-colors) for colour highlight.

**Comment by zootedb0t** [comment]
- [x] Add lsp-progress to statusline

**Comment by zootedb0t** [comment]
- [x] Update which-key config to v3

**Comment by zootedb0t** [comment]
- [x] Replace [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) with [blink.nvim](https://github.com/Saghen/blink.cmp)

**Comment by zootedb0t** [comment]
- [x] Improve `blink.nvim` keymap

**Comment by zootedb0t** [comment]
- [x] Replace [Telescope.nvim](https://github.com/nvim-telescope/telescope.nvim)

**Comment by zootedb0t** [comment]
- [ ] Improve [blink.cmp](https://github.com/Saghen/blink.cmp) keybindings
